### ISSUE TITLE
Report fails to compile due to missing benchmark images

### ISSUE THREAD

**Issue by gianluca-nitti** [dariost/scarlet#1]
Running `cd report && pdflatex -shell-escape main.tex` in a freshly cloned copy of this repository fails with
```
LaTeX Warning: File `benchmark/benchmark.png' not found on input line 314.


! Package pdftex.def Error: File `benchmark/benchmark.png' not found: using dra
ft setting.

See the pdftex.def package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.314 ...idth=\textwidth]{benchmark/benchmark.png}
```

`benchmark/4.png`, `benchmark/16.png` and `benchmark/64.png` are also missing.

The document can be compiled successfully by commenting out the 4 interested `\includegraphics` calls but of course this results in captions without images.

**Comment by dariost** [comment]
I've uploaded the missing images.

**Comment by gianluca-nitti** [comment]
I confirm it now compiles properly out of the box.
